In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.activity.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fexperimentsandconfigs%20https%3a%2f%2fwww.googleapis.com%2fauth%2fphotos.native&response_type=code

Enter your authorization code:
4/1AY0e-g63l-D8MkzVgAUt2HL3zKDuVazGGJjuXt_ZFiZNCoas45MN4HCcRCQ
Mounted at /content/drive


In [2]:
import os
os.getcwd()


'/content'

In [ ]:
!ls

In [3]:
os.chdir('/content/drive/My Drive/ANN')

In [4]:
os.getcwd()

'/content/drive/My Drive/ANN'

In [5]:
!ls

'Artificial Neural Network.ipynb'   Churn_Modelling.csv


In [6]:
import pandas as pd
dataset = pd.read_csv("Churn_Modelling.csv")

In [7]:
dataset.shape


(10000, 14)

In [8]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [9]:
dataset['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [ ]:
dataset.shape

In [ ]:
dataset.head()

In [10]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
features = dataset.iloc[:, 3:13].values
labels = dataset.iloc[:, 13].values

In [ ]:
type(features)

In [ ]:
features.shape

In [13]:
features[0:10,:]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 'Male', 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 'Female', 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 'Male', 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 'Male', 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [ ]:
dataset.dtypes

In [ ]:
features


In [ ]:
labels

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1,2])], remainder='passthrough')

features = np.array(columnTransformer.fit_transform(features), dtype = np.float32)



In [ ]:
features[0:10,:]


In [16]:

features = features[:, 1:] #drop the first dummy column for Geography


In [17]:
features[0]

array([0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
       6.1900000e+02, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05],
      dtype=float32)

In [18]:

features = features[:, [0,1,3,4,5,6,7,8,9,10,11]] #drop the column for Gender


In [19]:
features.shape

(10000, 11)

In [ ]:
features[0,:]

In [ ]:
features.shape

In [20]:
from sklearn.model_selection import train_test_split
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size = 0.2, random_state = 0)

In [ ]:
dataset.head()

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
features_train = sc.fit_transform(features_train)
features_test = sc.transform(features_test)

In [ ]:
features_train[0]

In [24]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [25]:
classifier = Sequential()

In [ ]:
features.shape

In [26]:
#adding the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [27]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation='sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [28]:
classifier.fit(features_train, labels_train, batch_size = 10, epochs = 10)

Epoch 1/10
800/800 [==============================] - 15s 2ms/step - loss: 0.5601 - accuracy: 0.7887
Epoch 2/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4179 - accuracy: 0.8004
Epoch 3/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4185 - accuracy: 0.8082
Epoch 4/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4182 - accuracy: 0.8257
Epoch 5/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4093 - accuracy: 0.8358
Epoch 6/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4065 - accuracy: 0.8358
Epoch 7/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4068 - accuracy: 0.8341
Epoch 8/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4029 - accuracy: 0.8372
Epoch 9/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3929 - accuracy: 0.8368
Epoch 10/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4003 - accuracy: 0.830

In [29]:
labels_pred = classifier.predict_classes(features_test)
#labels_pred = (labels_pred > 0.5)

/usr/local/lib/python3.7/dist-packages/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [30]:
labels_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [ ]:
len(labels_pred)

In [ ]:
list(zip(labels_test, labels_pred))

In [31]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, labels_pred)

In [32]:
cm


array([[1545,   50],
       [ 267,  138]])